// src/components/CombatPanel.jsx
export default function CombatPanel({
  armorClass,
  initiative,
  speed,
  onSpeedChange,
  charInfo,
  onCharInfoChange,
  hitDice,
  onHitDiceChange,
  deathSaves,
  onToggleDeathSave,
  attacks,
}) {
  return (
    <div className="md:col-span-4 space-y-4">
      {/* CA / Iniciativa / Velocidad */}
      <div className="grid grid-cols-3 gap-2">
        <div className="combat-main-box border border-black p-2 bg-white text-center rounded relative overflow-hidden">
          <span className="text-[0.5rem] font-bold uppercase absolute top-1 inset-x-0">
            Clase Armad.
          </span>
          <input
            type="number"
            className="text-3xl font-black text-center w-full mt-3 h-10 bg-transparent"
            value={armorClass}
            readOnly
          />
        </div>
        <div className="combat-main-box border border-black p-2 bg-white text-center rounded relative overflow-hidden">
          <span className="text-[0.5rem] font-bold uppercase absolute top-1 inset-x-0">
            Iniciativa
          </span>
          <div className="text-3xl font-black mt-3 h-10 flex items-center justify-center">
            {initiative >= 0 ? '+' : ''}
            {initiative}
          </div>
        </div>
        <div className="combat-main-box border border-black p-2 bg-white text-center rounded relative overflow-hidden">
          <span className="text-[0.5rem] font-bold uppercase absolute top-1 inset-x-0">
            Velocidad
          </span>
          <div className="mt-3 flex items-center justify-center">
            <input
              type="number"
              className="text-3xl font-black text-center w-full h-10 bg-transparent"
              value={speed}
              onChange={(e) => onSpeedChange(e.target.value)}
            />
            <span className="text-[0.6rem] font-bold absolute bottom-1">pies</span>
          </div>
        </div>
      </div>

      {/* HP */}
      <div className="border-2 border-black p-2 rounded bg-white shadow-md">
        <div className="flex justify-between items-center text-xs text-gray-500 mb-1 px-2">
          <label className="font-bold">Puntos de Golpe Máximos</label>
          <input
            type="number"
            value={charInfo.maxHp}
            onChange={(e) => onCharInfoChange({ maxHp: parseInt(e.target.value) })}
            className="w-12 text-right border-b border-gray-300"
          />
        </div>
        <input
          type="number"
          className="text-5xl font-black text-center w-full py-2"
          value={charInfo.currentHp}
          onChange={(e) => onCharInfoChange({ currentHp: parseInt(e.target.value) })}
        />
        <div className="text-center">
          <span className="text-[0.6rem] font-bold uppercase tracking-widest text-gray-700">
            Puntos de Golpe Actuales
          </span>
        </div>
      </div>

      {/* Temp HP */}
      <div className="border-2 border-black p-2 rounded bg-white shadow-sm text-center">
        <input
          type="number"
          className="text-3xl font-black text-center w-full text-gray-400 focus:text-black"
          placeholder="0"
        />
        <span className="text-[0.6rem] font-bold uppercase">Puntos de Golpe Temporales</span>
      </div>

      {/* Hit Dice & Death Saves */}
      <div className="grid grid-cols-2 gap-4">
        <div className="border-2 border-black p-2 rounded bg-white">
          <div className="flex justify-between text-[0.6rem] font-bold mb-1 border-b">
            <span>Total:</span>
            <input
              type="text"
              value={hitDice.total}
              onChange={(e) => onHitDiceChange({ total: e.target.value })}
              className="w-12 text-right"
            />
          </div>
          <input
            type="number"
            value={hitDice.current}
            onChange={(e) => onHitDiceChange({ current: e.target.value })}
            className="text-3xl font-black text-center w-full"
          />
          <div className="text-center text-[0.6rem] font-bold uppercase">Dados de Golpe</div>
        </div>

        <div className="border-2 border-black p-2 rounded bg-white">
          <div className="space-y-2 py-1">
            {['successes', 'failures'].map((type) => (
              <div className="flex items-center justify-between" key={type}>
                <span className="text-[0.5rem] font-bold uppercase w-12 text-right mr-1">
                  {type === 'successes' ? 'Éxitos' : 'Fallos'}
                </span>
                <div className="flex gap-2">
                  {deathSaves[type].map((val, i) => (
                    <div
                      key={i}
                      onClick={() => onToggleDeathSave(type, i)}
                      className={`w-4 h-4 rounded-full border border-black cursor-pointer ${
                        val
                          ? type === 'successes'
                            ? 'bg-black'
                            : 'bg-red-600'
                          : 'bg-white'
                      }`}
                    />
                  ))}
                </div>
              </div>
            ))}
          </div>
          <div className="text-center text-[0.6rem] font-bold uppercase mt-1">
            Salvaciones de Muerte
          </div>
        </div>
      </div>

      {/* Ataques */}
      <div className="border-2 border-black p-2 rounded bg-white shadow-inner">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b-2 border-gray-400">
              <th className="font-bold py-1 text-gray-500 uppercase text-[0.6rem] w-1/3">
                Nombre
              </th>
              <th className="font-bold py-1 text-gray-500 uppercase text-[0.6rem] text-center">
                Bono
              </th>
              <th className="font-bold py-1 text-gray-500 uppercase text-[0.6rem]">
                Daño / Tipo
              </th>
            </tr>
          </thead>
          <tbody>
            {attacks.map((atk, idx) => (
              <tr key={idx} className="border-b border-gray-200">
                <td className="py-2 font-bold bg-gray-50 px-1 border-r">{atk.name}</td>
                <td className="py-2 text-center font-bold border-r">{atk.bonus}</td>
                <td className="py-2 px-1 text-[0.7rem]">
                  {atk.damage}{' '}
                  <span className="text-gray-500 text-[0.6rem] block">{atk.type}</span>
                </td>
              </tr>
            ))}
            <tr>
              <td className="py-3 px-1 border-r bg-gray-50">
                <input type="text" className="w-full bg-transparent" placeholder="..." />
              </td>
              <td className="py-3 border-r">
                <input type="text" className="w-full text-center bg-transparent" />
              </td>
              <td className="py-3 px-1">
                <input type="text" className="w-full bg-transparent" />
              </td>
            </tr>
          </tbody>
        </table>
        <div className="mt-2 border-t pt-1">
          <textarea
            className="w-full h-20 text-[0.65rem] resize-none p-1"
            placeholder="Ataques adicionales, munición, notas..."
            defaultValue={`Ira Frustrada (Furia): +2 daño cuerpo a cuerpo.\nLanzar jabalina: 30/120 pies.`}
          />
        </div>
      </div>
    </div>
  );
}

// src/components/CombatPanel.vue
<script setup>
import { computed } from 'vue'

const props = defineProps({
  armorClass: { type: Number, required: true },
  initiative: { type: Number, required: true },
  speed: { type: Number, required: true },
  charInfo: { type: Object, required: true },
  hitDice: { type: Object, required: true },
  deathSaves: { type: Object, required: true },
  attacks: { type: Array, required: true },
})

const emit = defineEmits(['speedChange', 'charInfoChange', 'hitDiceChange', 'toggleDeathSave'])

const hpColorClass = computed(() => {
  const ratio = props.charInfo.currentHp / props.charInfo.maxHp
  if (ratio >= 1) return 'text-green-600'
  if (ratio >= 0.5) return 'text-green-500'
  if (ratio >= 0.25) return 'text-amber-500'
  return 'text-red-600 animate-pulse'
})
</script>

<template>
  <div class="md:col-span-4 space-y-4">
    <div class="section-banner">Combate</div>
    
    <!-- CA / Iniciativa / Velocidad -->
    <div class="grid grid-cols-3 gap-3">
      <div class="ca-shield">
        <span class="text-[0.6rem] font-black uppercase text-dnd-red block mb-1">Clase Armad.</span>
        <div class="text-4xl font-black text-dnd-dark drop-shadow-sm">{{ armorClass }}</div>
      </div>
      
      <div class="border-2 border-black p-2 bg-white text-center rounded-xl relative shadow-sm h-full flex flex-col justify-center">
        <span class="text-[0.5rem] font-bold uppercase block text-gray-400">Iniciativa</span>
        <div class="text-3xl font-black mt-1 flex items-center justify-center">
          {{ initiative >= 0 ? '+' : '' }}{{ initiative }}
        </div>
      </div>

      <div class="border-2 border-black p-2 bg-white text-center rounded-xl relative shadow-sm h-full flex flex-col justify-center">
        <span class="text-[0.5rem] font-bold uppercase block text-gray-400">Velocidad</span>
        <div class="mt-1 flex flex-col items-center justify-center relative">
          <input
            type="number"
            class="text-3xl font-black text-center w-full bg-transparent outline-none"
            :value="speed"
            @change="emit('speedChange', Number($event.target.value))"
          />
          <span class="text-[0.5rem] font-bold uppercase absolute -bottom-1 right-0 text-gray-300">pies</span>
        </div>
      </div>
    </div>

    <!-- Puntos de Golpe -->
    <div class="border-2 border-black rounded-xl bg-white shadow-md overflow-hidden">
      <div class="flex justify-between items-center bg-gray-50 px-3 py-1 border-b border-black">
        <label class="text-[0.6rem] font-black uppercase tracking-wider text-gray-400">Puntos de Golpe Máximos</label>
        <div class="flex items-center gap-1">
          <span class="text-[0.6rem] font-bold text-gray-300 uppercase">HP Máx</span>
          <input
            type="number"
            :value="charInfo.maxHp"
            @change="emit('charInfoChange', { maxHp: parseInt($event.target.value) })"
            class="w-10 text-center font-black text-sm bg-transparent border-b border-gray-200 focus:border-dnd-red outline-none"
          />
        </div>
      </div>
      
      <div class="p-2 flex flex-col items-center justify-center py-4">
        <input
          type="number"
          class="text-6xl font-black text-center w-full bg-transparent transition-colors duration-500 outline-none"
          :class="hpColorClass"
          :value="charInfo.currentHp"
          @change="emit('charInfoChange', { currentHp: parseInt($event.target.value) })"
        />
        <span class="text-[0.6rem] font-black uppercase tracking-[0.2em] text-gray-400 mt-2">
          Puntos de Golpe Actuales
        </span>
      </div>
    </div>

    <!-- Temp HP & Dados de Golpe & Salvaciones -->
    <div class="grid grid-cols-2 gap-4">
      <div class="space-y-4">
        <div class="border-2 border-black p-2 rounded-xl bg-white shadow-sm text-center">
          <input
            type="number"
            class="text-3xl font-black text-center w-full text-gray-200 focus:text-black bg-transparent outline-none"
            placeholder="0"
          />
          <span class="text-[0.5rem] font-bold uppercase text-gray-400 block border-t mt-1 pt-1">PTOS Temporales</span>
        </div>

        <div class="border-2 border-black p-2 rounded-xl bg-white shadow-sm">
          <div class="flex justify-between text-[0.6rem] font-black mb-1 border-b border-gray-100 uppercase tracking-widest text-gray-400">
            <span>Total:</span>
            <input
              type="text"
              :value="hitDice.total"
              @change="emit('hitDiceChange', { total: $event.target.value })"
              class="w-10 text-right font-bold bg-transparent outline-none"
            />
          </div>
          <input
            type="number"
            :value="hitDice.current"
            @change="emit('hitDiceChange', { current: parseInt($event.target.value) })"
            class="text-3xl font-black text-center w-full py-1 bg-transparent outline-none"
          />
          <div class="text-center text-[0.5rem] font-bold uppercase text-gray-500 pt-1 border-t">Dados de Golpe</div>
        </div>
      </div>

      <div class="border-2 border-black p-2 rounded-xl bg-white shadow-sm flex flex-col justify-between overflow-hidden">
        <div class="space-y-4 py-2">
          <div
            v-for="type in ['successes', 'failures']"
            :key="type"
            class="flex items-center justify-between"
          >
            <span class="text-[0.55rem] font-black uppercase w-12 text-gray-400 leading-none">
              {{ type === 'successes' ? 'Éxitos' : 'Fallos' }}
            </span>
            <div class="flex gap-2">
              <div
                v-for="(val, i) in deathSaves[type]"
                :key="i"
                @click="emit('toggleDeathSave', type, i)"
                :class="[
                  'w-5 h-5 rounded-full border-2 border-black cursor-pointer shadow-sm transition-all',
                  val
                    ? type === 'successes' ? 'bg-black' : 'bg-red-600'
                    : 'bg-white hover:border-gray-400'
                ]"
              />
            </div>
          </div>
        </div>
        <div class="text-center text-[0.5rem] font-black uppercase text-gray-500 border-t pt-2 mt-2">
          Salvaciones de Muerte
        </div>
      </div>
    </div>

    <!-- Ataques (Scrollable horizontal on mobile) -->
    <div class="border-2 border-black rounded-xl bg-white shadow-md overflow-hidden">
      <div class="section-banner w-full text-center py-1">Ataques y Conjuros</div>
      <div class="overflow-x-auto">
        <table class="w-full text-left text-xs min-w-[300px]">
          <thead>
            <tr class="bg-gray-50 border-b-2 border-black">
              <th class="font-black py-2 px-3 text-dnd-red uppercase text-[0.6rem]">Nombre</th>
              <th class="font-black py-2 text-center text-dnd-red uppercase text-[0.6rem] w-12">Bono</th>
              <th class="font-black py-2 px-3 text-dnd-red uppercase text-[0.6rem]">Daño / Tipo</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(atk, idx) in attacks" :key="idx" class="border-b border-gray-100 hover:bg-red-50/30 transition-colors">
              <td class="py-2 px-3 font-bold border-r table-cell align-middle">{{ atk.name }}</td>
              <td class="py-2 text-center font-black border-r text-sm align-middle">{{ atk.bonus }}</td>
              <td class="py-2 px-3 text-[0.7rem] bg-gray-50/50 align-middle">
                <div class="font-bold">{{ atk.damage }}</div>
                <div class="text-[0.6rem] text-gray-400 uppercase font-bold">{{ atk.type }}</div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="p-2 border-t bg-gray-50">
        <textarea
          class="w-full h-20 text-[0.7rem] font-medium resize-none p-2 bg-white rounded border border-gray-200 focus:outline-none focus:border-dnd-red"
          placeholder="Notas de combate..."
        >Ira Frustrada (Furia): +2 daño cuerpo a cuerpo.
Lanzar jabalina: 30/120 pies.</textarea>
      </div>
    </div>
  </div>
</template>
