// src/App.jsx
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

// Componentes
import DiceTray from './components/DiceTray';
import CharacterStats from './components/CharacterStats';
import SkillsPanel from './components/SkillsPanel';
import CombatPanel from './components/CombatPanel';
import PersonalityPanel from './components/PersonalityPanel';
import BioTab from './components/BioTab';

// Datos y utilidades
import {
  INITIAL_STATS,
  INITIAL_CHAR_INFO,
  INITIAL_PROFICIENCIES,
  INITIAL_ATTACKS,
  INITIAL_EQUIPMENT,
  INITIAL_FEATURES,
  INITIAL_COINS,
} from './constants/dndData';
import { getMod } from './utils/modifiers';
import { exportToExcel } from './utils/exportExcel';

function App() {
  const [activeTab, setActiveTab] = useState('main');

  // Estado del personaje
  const [stats, setStats] = useState(INITIAL_STATS);
  const [charInfo, setCharInfo] = useState(INITIAL_CHAR_INFO);
  const [proficiencies, setProficiencies] = useState(INITIAL_PROFICIENCIES);
  const [speed, setSpeed] = useState(30);
  const [hitDice, setHitDice] = useState({ total: '1d12', current: 1 });
  const [deathSaves, setDeathSaves] = useState({
    successes: [false, false, false],
    failures: [false, false, false],
  });
  const [coins, setCoins] = useState(INITIAL_COINS);

  // Valores derivados
  const armorClass = 10 + getMod(stats.destreza) + getMod(stats.constitucion);
  const initiative = getMod(stats.destreza);

  // Handlers
  const handleStatChange = (stat, val) =>
    setStats((prev) => ({ ...prev, [stat]: parseInt(val) || 0 }));

  const handleCharInfoChange = (changes) =>
    setCharInfo((prev) => ({ ...prev, ...changes }));

  const toggleSave = (stat) =>
    setProficiencies((prev) => ({
      ...prev,
      saves: { ...prev.saves, [stat]: !prev.saves[stat] },
    }));

  const toggleSkill = (skill) =>
    setProficiencies((prev) => ({
      ...prev,
      skills: { ...prev.skills, [skill]: !prev.skills[skill] },
    }));

  const toggleDeathSave = (type, index) =>
    setDeathSaves((prev) => {
      const updated = [...prev[type]];
      updated[index] = !updated[index];
      return { ...prev, [type]: updated };
    });

  const handleExport = () =>
    exportToExcel({
      charInfo,
      stats,
      equipment: INITIAL_EQUIPMENT,
      armorClass,
      initiative,
      speed,
      hitDice,
      getMod,
    });

  const handleReset = () => {
    if (confirm('¿Reiniciar memoria?')) window.location.reload();
  };

  return (
    <div className="min-h-screen p-2 md:p-6">
      <div className="max-w-5xl mx-auto">
        {/* NAV */}
        <nav className="flex gap-1 no-print">
          <button
            onClick={() => setActiveTab('main')}
            className={`tab-btn ${activeTab === 'main' ? 'active' : 'inactive'}`}
          >
            ⚔️ Amnesia y Combate
          </button>
          <button
            onClick={() => setActiveTab('bio')}
            className={`tab-btn ${activeTab === 'bio' ? 'active' : 'inactive'}`}
          >
            📜 Búsqueda sin Nombre
          </button>
        </nav>

        <div className="parchment-bg rounded-b-lg p-4 md:p-8 shadow-2xl">
          {/* HEADER */}
          <header className="grid grid-cols-1 md:grid-cols-12 gap-4 mb-8 items-end border-b-2 border-black/20 pb-4">
            <div className="md:col-span-4">
              <label className="text-[0.6rem] font-bold uppercase text-red-900">El Olvidado</label>
              <input
                type="text"
                className="text-2xl font-bold header-font"
                value={charInfo.name}
                onChange={(e) => handleCharInfoChange({ name: e.target.value })}
              />
            </div>
            <div className="md:col-span-8 grid grid-cols-2 md:grid-cols-4 gap-x-2 gap-y-2">
              {[
                { label: 'Clase/Nivel', key: 'classLevel' },
                { label: 'Trasfondo', key: 'background' },
                { label: 'Raza', key: 'race' },
              ].map(({ label, key }) => (
                <div key={key}>
                  <label className="text-[0.6rem] font-bold uppercase">{label}</label>
                  <input
                    type="text"
                    value={charInfo[key]}
                    onChange={(e) => handleCharInfoChange({ [key]: e.target.value })}
                    className="font-bold"
                  />
                </div>
              ))}
              <div>
                <label className="text-[0.6rem] font-bold uppercase">Esencia</label>
                <input type="text" value="Recuerdo Borroso" className="font-bold text-gray-500" readOnly />
              </div>
            </div>
          </header>

          {/* TAB MAIN */}
          <AnimatePresence mode="wait">
            {activeTab === 'main' && (
              <motion.div
                key="main"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                transition={{ duration: 0.3 }}
                className="grid grid-cols-1 md:grid-cols-12 gap-6"
              >
                <CharacterStats stats={stats} onStatChange={handleStatChange} />
                <SkillsPanel
                  stats={stats}
                  proficiencies={proficiencies}
                  onToggleSave={toggleSave}
                  onToggleSkill={toggleSkill}
                />
                <CombatPanel
                  armorClass={armorClass}
                  initiative={initiative}
                  speed={speed}
                  onSpeedChange={setSpeed}
                  charInfo={charInfo}
                  onCharInfoChange={handleCharInfoChange}
                  hitDice={hitDice}
                  onHitDiceChange={(changes) => setHitDice((prev) => ({ ...prev, ...changes }))}
                  deathSaves={deathSaves}
                  onToggleDeathSave={toggleDeathSave}
                  attacks={INITIAL_ATTACKS}
                />
                <PersonalityPanel features={INITIAL_FEATURES} />
              </motion.div>
            )}
          </AnimatePresence>

          {/* TAB BIO */}
          <AnimatePresence mode="wait">
            {activeTab === 'bio' && (
              <motion.div
                key="bio"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
              >
                <BioTab
                  stats={stats}
                  equipment={INITIAL_EQUIPMENT}
                  coins={coins}
                  onCoinsChange={setCoins}
                />
              </motion.div>
            )}
          </AnimatePresence>

          {/* FOOTER */}
          <footer className="mt-8 flex flex-wrap justify-center gap-4 no-print border-t pt-6">
            <button
              onClick={() => window.print()}
              className="bg-gray-800 text-white px-8 py-3 rounded-full font-bold shadow-lg hover:bg-black transition flex items-center gap-2"
            >
              🖨️ PDF de Iteración
            </button>
            <button
              onClick={handleExport}
              className="bg-green-700 text-white px-8 py-3 rounded-full font-bold shadow-lg hover:bg-green-800 transition flex items-center gap-2"
            >
              📊 Exportar Memoria a Excel
            </button>
            <button
              onClick={handleReset}
              className="bg-red-800 text-white px-8 py-3 rounded-full font-bold shadow-lg hover:bg-red-900 transition flex items-center gap-2"
            >
              ♻️ Reiniciar
            </button>
          </footer>
        </div>

        <DiceTray />
      </div>
    </div>
  );
}

export default App;

// src/App.vue
<script setup>
import { ref, computed } from 'vue'

import DiceTray from './components/DiceTray.vue'
import CharacterStats from './components/CharacterStats.vue'
import SkillsPanel from './components/SkillsPanel.vue'
import CombatPanel from './components/CombatPanel.vue'
import PersonalityPanel from './components/PersonalityPanel.vue'
import BioTab from './components/BioTab.vue'

import {
  INITIAL_STATS,
  INITIAL_CHAR_INFO,
  INITIAL_PROFICIENCIES,
  INITIAL_ATTACKS,
  INITIAL_EQUIPMENT,
  INITIAL_FEATURES,
  INITIAL_COINS,
} from './constants/dndData'
import { getMod } from './utils/modifiers'
import { exportToExcel } from './utils/exportExcel'

const activeTab = ref('main')

const stats = ref({ ...INITIAL_STATS })
const charInfo = ref({ ...INITIAL_CHAR_INFO })
const proficiencies = ref({
  saves: { ...INITIAL_PROFICIENCIES.saves },
  skills: { ...INITIAL_PROFICIENCIES.skills },
})
const speed = ref(30)
const hitDice = ref({ total: '1d12', current: 1 })
const deathSaves = ref({
  successes: [false, false, false],
  failures: [false, false, false],
})
const coins = ref({ ...INITIAL_COINS })

const armorClass = computed(() => 10 + getMod(stats.value.destreza) + getMod(stats.value.constitucion))
const initiative = computed(() => getMod(stats.value.destreza))

function handleStatChange(stat, val) {
  stats.value = { ...stats.value, [stat]: parseInt(val) || 0 }
}

function handleCharInfoChange(changes) {
  charInfo.value = { ...charInfo.value, ...changes }
}

function toggleSave(stat) {
  proficiencies.value = {
    ...proficiencies.value,
    saves: { ...proficiencies.value.saves, [stat]: !proficiencies.value.saves[stat] },
  }
}

function toggleSkill(skill) {
  proficiencies.value = {
    ...proficiencies.value,
    skills: { ...proficiencies.value.skills, [skill]: !proficiencies.value.skills[skill] },
  }
}

function toggleDeathSave(type, index) {
  const updated = [...deathSaves.value[type]]
  updated[index] = !updated[index]
  deathSaves.value = { ...deathSaves.value, [type]: updated }
}

function handleHitDiceChange(changes) {
  hitDice.value = { ...hitDice.value, ...changes }
}

function handleExport() {
  exportToExcel({
    charInfo: charInfo.value,
    stats: stats.value,
    equipment: INITIAL_EQUIPMENT,
    armorClass: armorClass.value,
    initiative: initiative.value,
    speed: speed.value,
    hitDice: hitDice.value,
    getMod,
  })
}

function handleReset() {
  if (confirm('¿Reiniciar memoria?')) window.location.reload()
}
</script>

<template>
  <div class="min-h-screen p-2 sm:p-4 md:p-6 bg-gray-50">
    <div class="max-w-5xl mx-auto">
      <!-- NAV -->
      <nav class="flex w-full no-print">
        <button
          @click="activeTab = 'main'"
          :class="['tab-btn', activeTab === 'main' ? 'active' : 'inactive']"
        >
          ⚔️ Amnesia y Combate
        </button>
        <button
          @click="activeTab = 'bio'"
          :class="['tab-btn', activeTab === 'bio' ? 'active' : 'inactive']"
        >
          📜 Búsqueda sin Nombre
        </button>
      </nav>

      <div class="parchment-bg rounded-b-xl p-3 sm:p-5 md:p-8 shadow-2xl border-x-2 border-b-2 border-black/5">
        <!-- HEADER -->
        <header class="grid grid-cols-1 md:grid-cols-12 gap-6 mb-8 items-end border-b-4 border-dnd-red/20 pb-6">
          <div class="md:col-span-5">
            <label class="text-[0.6rem] font-black uppercase text-dnd-red tracking-widest block mb-1">Nombre del Personaje</label>
            <input
              type="text"
              class="text-3xl font-bold header-font w-full bg-transparent outline-none focus:border-b-2 border-dnd-gold"
              :value="charInfo.name"
              @input="handleCharInfoChange({ name: $event.target.value })"
            />
          </div>
          <div class="md:col-span-7 grid grid-cols-2 md:grid-cols-4 gap-x-3 gap-y-3">
            <div v-for="field in [
              { label: 'Clase/Nivel', key: 'classLevel' },
              { label: 'Trasfondo', key: 'background' },
              { label: 'Raza/Especie', key: 'race' },
            ]" :key="field.key">
              <label class="text-[0.55rem] font-bold uppercase text-gray-400 block">{{ field.label }}</label>
              <input
                type="text"
                :value="charInfo[field.key]"
                @input="handleCharInfoChange({ [field.key]: $event.target.value })"
                class="font-black text-sm w-full bg-transparent border-b border-gray-100 py-1 outline-none focus:border-dnd-red"
              />
            </div>
            <div>
              <label class="text-[0.55rem] font-bold uppercase text-gray-400 block">Esencia</label>
              <input type="text" value="Recuerdo Borroso" class="font-black text-sm text-gray-400 bg-transparent w-full border-b border-gray-100 py-1" readonly />
            </div>
          </div>
        </header>

        <!-- TAB MAIN -->
        <Transition name="tab" mode="out-in">
          <div
            v-if="activeTab === 'main'"
            key="main"
            class="grid grid-cols-1 md:grid-cols-12 gap-8"
          >
            <!-- Lado Izquierdo: Stats + Skills -->
            <div class="md:col-span-5 grid grid-cols-1 md:grid-cols-5 gap-6">
              <CharacterStats
                :stats="stats"
                @statChange="handleStatChange"
              />
              <SkillsPanel
                :stats="stats"
                :proficiencies="proficiencies"
                @toggleSave="toggleSave"
                @toggleSkill="toggleSkill"
              />
            </div>

            <!-- Lado Derecho: Combate + Personalidad -->
            <div class="md:col-span-7 space-y-8">
              <CombatPanel
                :armorClass="armorClass"
                :initiative="initiative"
                :speed="speed"
                :charInfo="charInfo"
                :hitDice="hitDice"
                :deathSaves="deathSaves"
                :attacks="INITIAL_ATTACKS"
                @speedChange="(v) => (speed = parseInt(v) || 0)"
                @charInfoChange="handleCharInfoChange"
                @hitDiceChange="handleHitDiceChange"
                @toggleDeathSave="toggleDeathSave"
              />
              <PersonalityPanel :features="INITIAL_FEATURES" />
            </div>
          </div>

          <!-- TAB BIO -->
          <div v-else-if="activeTab === 'bio'" key="bio">
            <BioTab
              :stats="stats"
              :equipment="INITIAL_EQUIPMENT"
              :coins="coins"
              @coinsChange="(v) => (coins = v)"
            />
          </div>
        </Transition>

        <!-- FOOTER -->
        <footer class="mt-12 flex flex-col sm:flex-row justify-center items-center gap-4 no-print border-t border-black/10 pt-8">
          <button
            @click="window.print()"
            class="w-full sm:w-auto bg-dnd-red text-white px-8 py-3 rounded-xl font-black shadow-lg hover:bg-black transition-all flex items-center justify-center gap-2 uppercase text-xs tracking-widest"
          >
            🖨️ PDF de Hoja
          </button>
          <button
            @click="handleExport"
            class="w-full sm:w-auto bg-green-700 text-white px-8 py-3 rounded-xl font-black shadow-lg hover:bg-green-800 transition-all flex items-center justify-center gap-2 uppercase text-xs tracking-widest"
          >
            📊 Exportar a Excel
          </button>
          <button
            @click="handleReset"
            class="w-full sm:w-auto bg-gray-200 text-gray-500 px-8 py-3 rounded-xl font-black shadow hover:bg-gray-300 transition-all flex items-center justify-center gap-2 uppercase text-xs tracking-widest"
          >
            ♻️ Reiniciar
          </button>
        </footer>
      </div>

      <!-- El dado ahora vive en su propio tray con FAB -->
      <DiceTray />
    </div>
  </div>
</template>
